---
booktitle: Active Learning and Experimental Design workshop In conjunction with AISTATS
  2010
logoright: logo.png
year: '2010'
supplementalurl: supplemental/JMLRWCP_V16_supplemental.html
month: 0
publisher: JMLR Workshop and Conference Proceedings
volume: 16
start: 2010-05-16
end: 2010-05-16
published: 2011-04-21
shortname: Active Learning and Experimental Design Workshop
sections:
- name: tutorial
  title: Tutorial
- name: default
  title: Active Learning Challenge
- name: studies
  title: Case Studies in Active Learning
layout: proceedings
series: Proceedings of Machine Learning Research
id: GuyonActive2010
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
editor:
- given: Isabelle
  family: Guyon
- given: Gavin
  family: Cawley
- given: Gideon
  family: Dror
- given: Vincent
  family: Lemaire
- given: Alexander
  family: Statnikov
description: |
  Active Learning and Experimental Design workshop In conjunction with AISTATS 2010
    Held in Sardinia, Italy on 16 May 2010

  Published as Volume 16 by the Proceedings of Machine Learning Research on 21 April 2011.

  Volume Edited by:
    Isabelle Guyon
    Gavin Cawley
    Gideon Dror
    Vincent Lemaire
    Alexander Statnikov

  Series Editors:
    Neil D. Lawrence
date_str: 16 May
url: http://proceedings.mlr.press
baseurl: "/v16"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v16
bibtex_copy: true
endnote_copy: true
apa_copy: true
email: ''
conference:
  name: Active Learning and Experimental Design workshop In conjunction with AISTATS
    2010
  url: 
  location: Sardinia, Italy
  dates:
  - 2010-05-16
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v16.bib
